---
version: '3'

silent: true

tasks:
  default:
    cmds:
      - task --list-all
    ignore_error: true

  check:
    cmds:
      - swiftlint --fix {{.file}}
      - swift {{.file}}
    vars:
      file:
        sh: git ls-files --other --modified --exclude-standard -- '*.swift'
    ignore_error: true

  changelog:
    cmds:
      - bash update_progress.sh
    ignore_error: true
