---
version: '3'

silent: false

tasks:

  default:
    summary: |
      Just a list of documented tasks.
    silent: true
    cmds:
      - task --list-all

  lint:
    cmds:
      - swiftlint --fix {{.file}}
    silent: true
    vars:
      file:
        sh: git ls-files --other --modified --exclude-standard -- '*.swift'
    ignore_error: true
  
  check:
    cmds:
      - swift {{.file}}
    vars:
      file:
        sh: git ls-files --other --modified --exclude-standard -- '*.swift'
    ignore_error: true

  changelog:
    deps:
      - lint
    cmds:
      - bash update_progress.sh
    ignore_error: true
